package org.thepalaceproject.webpub.core

import com.fasterxml.jackson.databind.BeanDescription
import com.fasterxml.jackson.databind.JsonSerializer
import com.fasterxml.jackson.databind.Module
import com.fasterxml.jackson.databind.SerializationConfig
import com.fasterxml.jackson.databind.module.SimpleDeserializers
import com.fasterxml.jackson.databind.module.SimpleModule
import com.fasterxml.jackson.databind.ser.BeanSerializerModifier
import com.io7m.dixmont.core.DmJsonRestrictedDeserializers
import one.irradia.mime.api.MIMEType
import java.net.URI
import java.time.OffsetDateTime

object WPMModule {

  fun createDeserializers() : SimpleDeserializers {
    return DmJsonRestrictedDeserializers.builder()
      .allowClass(Boolean::class.javaPrimitiveType)
      .allowClass(Double::class.javaPrimitiveType)
      .allowClass(Int::class.javaPrimitiveType)
      .allowClass(Integer::class.java)
      .allowClass(MIMEType::class.java)
      .allowClass(Number::class.java)
      .allowClass(OffsetDateTime::class.java)
      .allowClass(String::class.java)
      .allowClass(URI::class.java)
      .allowClass(WPMAccessibility.AccessMode::class.java)
      .allowClass(WPMAccessibility.AccessModeSufficient::class.java)
      .allowClass(WPMAccessibility.Certification::class.java)
      .allowClass(WPMAccessibility.Exemption::class.java)
      .allowClass(WPMAccessibility.Feature::class.java)
      .allowClass(WPMAccessibility.Hazard::class.java)
      .allowClass(WPMAccessibility::class.java)
      .allowClass(WPMArticle::class.java)
      .allowClass(WPMArticle.WPMArticleObject::class.java)
      .allowClass(WPMAvailability::class.java)
      .allowClass(WPMBelongsTo::class.java)
      .allowClass(WPMCatalog::class.java)
      .allowClass(WPMChapter.WPMChapterObject::class.java)
      .allowClass(WPMChapter::class.java)
      .allowClass(WPMCollection::class.java)
      .allowClass(WPMCollection.WPMCollectionObject::class.java)
      .allowClass(WPMContains::class.java)
      .allowClass(WPMContributor::class.java)
      .allowClass(WPMContributorOrString::class.java)
      .allowClass(WPMEncrypted::class.java)
      .allowClass(WPMEpisode::class.java)
      .allowClass(WPMEpisode.WPMEpisodeObject::class.java)
      .allowClass(WPMIndirectAcquisitionTree::class.java)
      .allowClass(WPMIssue::class.java)
      .allowClass(WPMIssue.WPMIssueObject::class.java)
      .allowClass(WPMLanguageMap::class.java)
      .allowClass(WPMLayout::class.java)
      .allowClass(WPMLink::class.java)
      .allowClass(WPMLinkDeserializer.WPMLinkRaw::class.java)
      .allowClass(WPMLinkProperties::class.java)
      .allowClass(WPMManifest::class.java)
      .allowClass(WPMMetadata::class.java)
      .allowClass(WPMPeriodical::class.java)
      .allowClass(WPMPeriodical.WPMPeriodicalObject::class.java)
      .allowClass(WPMPublication::class.java)
      .allowClass(WPMReadingProgression::class.java)
      .allowClass(WPMSeason::class.java)
      .allowClass(WPMSeason.WPMSeasonObject::class.java)
      .allowClass(WPMSeries::class.java)
      .allowClass(WPMSeries.WPMSeriesObject::class.java)
      .allowClass(WPMStoryArc::class.java)
      .allowClass(WPMStoryArc.WPMStoryArcObject::class.java)
      .allowClass(WPMSubject::class.java)
      .allowClass(WPMSubjectOrString::class.java)
      .allowClass(WPMVolume::class.java)
      .allowClass(WPMVolume.WPMVolumeObject::class.java)
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMSeason>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMArticle>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMSeries>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMIssue>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMVolume>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMEpisode>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMChapter>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMStoryArc>")
      .allowClassName("java.util.List<java.lang.String>")
      .allowClassName("java.util.List<java.net.URI>")
      .allowClassName("java.util.List<java.util.List<org.thepalaceproject.webpub.core.WPMAccessibility\$AccessModeSufficient>>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMAccessibility\$AccessMode>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMAccessibility\$AccessModeSufficient>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMAccessibility\$Feature>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMAccessibility\$Hazard>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMCatalog>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMContributorOrString>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMIndirectAcquisitionTree>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMLink>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMLinkDeserializer\$WPMLinkRaw>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMNavigation>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMNavigationLink>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMPublication>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMSubject>")
      .allowClassName("java.util.List<org.thepalaceproject.webpub.core.WPMSubjectOrString>")
      .allowClassName("java.util.Map<java.lang.String,java.lang.String>")
      .allowClassName("java.util.Set<java.lang.String>")
      .build()
  }

  fun create() : Module {
    val module = SimpleModule()
    module.setDeserializers(this.createDeserializers())

    module.addDeserializer(MIMEType::class.java, WPMMIMETypeDeserializer())
    module.addDeserializer(OffsetDateTime::class.java, WPMOffsetDateTimeDeserializer())
    module.addDeserializer(WPMArticle::class.java, WPMArticleDeserializer())
    module.addDeserializer(WPMChapter::class.java, WPMChapterDeserializer())
    module.addDeserializer(WPMCollection::class.java, WPMCollectionDeserializer())
    module.addDeserializer(WPMContributorOrString::class.java, WPMContributorOrStringDeserializer())
    module.addDeserializer(WPMEpisode::class.java, WPMEpisodeDeserializer())
    module.addDeserializer(WPMIssue::class.java, WPMIssueDeserializer())
    module.addDeserializer(WPMLanguageMap::class.java, WPMLanguageMapDeserializer())
    module.addDeserializer(WPMLink::class.java, WPMLinkDeserializer())
    module.addDeserializer(WPMPeriodical::class.java, WPMPeriodicalDeserializer())
    module.addDeserializer(WPMSeason::class.java, WPMSeasonDeserializer())
    module.addDeserializer(WPMSeries::class.java, WPMSeriesDeserializer())
    module.addDeserializer(WPMStoryArc::class.java, WPMStoryArcDeserializer())
    module.addDeserializer(WPMSubjectOrString::class.java, WPMSubjectOrStringDeserializer())
    module.addDeserializer(WPMVolume::class.java, WPMVolumeDeserializer())

    module.addSerializer(OffsetDateTime::class.java, WPMOffsetDateTimeSerializer())
    module.addSerializer(WPMArticle::class.java, WPMArticleSerializer())
    module.addSerializer(WPMChapter::class.java, WPMChapterSerializer())
    module.addSerializer(WPMCollection::class.java, WPMCollectionSerializer())
    module.addSerializer(WPMContributorOrString::class.java, WPMContributorOrStringSerializer())
    module.addSerializer(WPMEpisode::class.java, WPMEpisodeSerializer())
    module.addSerializer(WPMIssue::class.java, WPMIssueSerializer())
    module.addSerializer(WPMLanguageMap::class.java, WPMLanguageMapSerializer())
    module.addSerializer(WPMLink::class.java, WPMLinkSerializer())
    module.addSerializer(WPMPeriodical::class.java, WPMPeriodicalSerializer())
    module.addSerializer(WPMSeason::class.java, WPMSeasonSerializer())
    module.addSerializer(WPMSeries::class.java, WPMSeriesSerializer())
    module.addSerializer(WPMStoryArc::class.java, WPMStoryArcSerializer())
    module.addSerializer(WPMSubjectOrString::class.java, WPMSubjectOrStringSerializer())
    module.addSerializer(WPMVolume::class.java, WPMVolumeSerializer())

    return module
  }
}
