name: Create Release

on: workflow_dispatch

permissions:
  contents: read

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          java-version: 21
          distribution: temurin
      - name: Finish release
        run: .ci/ci-release-finish.sh
      - name: Build
        env:
          MAVEN_CENTRAL_USERNAME:           ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD:           ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_CENTRAL_STAGING_PROFILE_ID: ${{ secrets.MAVEN_CENTRAL_STAGING_PROFILE_ID }}
          MAVEN_CENTRAL_SIGNING_KEY_ID:     ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_ID }}
          CI_GITHUB_ACCESS_TOKEN:           ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
        run: .ci/ci-main.sh normal
