name: Android CI (Pull Requests)

on:
  pull_request:
    branches: [ main, feature/* ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          java-version: 21
          distribution: temurin
      - name: Build PR
        run: .ci/ci-main.sh pull-request

